### ISSUE TITLE
unhandled promise rejection: Cannot read property 'getRawPacket' of null

### ISSUE THREAD

**Issue by D3ltorohd** [ioBroker/ioBroker.maxcul#48]
Hm nach Update von node und dem Controller, hatte ich Probleme den Adapter zu starten, hab dann ja @serialport gelöscht und über git neu installiert.

Danach startete der Adapter und es kam auch kein Fehler in der Log, hatte auch Testhalber mal Temps an einen HT gesendet, der hat direkt reagiert. Jetzt schau ich in der Log, etwas später nun steht folgendes drin..

`

maxcul.0 | 2020-05-19 19:19:18.380 | info | (18098) terminating
-- | -- | -- | --
maxcul.0 | 2020-05-19 19:19:18.336 | info | (18098) Terminated (NO_ERROR): Without reason
maxcul.0 | 2020-05-19 19:19:18.335 | info | (18098) terminating
maxcul.0 | 2020-05-19 19:19:17.529 | error | at processImmediate (internal/timers.js:456:21)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at Immediate.Async.drainQueues [as _onImmediate] (/opt/iobroker/node_modules/bluebird/js/release/async.js:15:14)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at Async._drainQueues (/opt/iobroker/node_modules/bluebird/js/release/async.js:102:5)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at _drainQueue (/opt/iobroker/node_modules/bluebird/js/release/async.js:86:9)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at _drainQueueStep (/opt/iobroker/node_modules/bluebird/js/release/async.js:93:12)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at Promise._settlePromises (/opt/iobroker/node_modules/bluebird/js/release/promise.js:725:18)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at Promise._settlePromise0 (/opt/iobroker/node_modules/bluebird/js/release/promise.js:649:10)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at Promise._settlePromise (/opt/iobroker/node_modules/bluebird/js/release/promise.js:604:18)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at Promise._settlePromiseFromHandler (/opt/iobroker/node_modules/bluebird/js/release/promise.js:547:31)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at tryCatcher (/opt/iobroker/node_modules/bluebird/js/release/util.js:16:23)
maxcul.0 | 2020-05-19 19:19:17.529 | error | at /opt/iobroker/node_modules/iobroker.maxcul/lib/communication-layer.js:331:61
maxcul.0 | 2020-05-19 19:19:17.529 | error | (18098) TypeError: Cannot read property 'getRawPacket' of null
maxcul.0 | 2020-05-19 19:19:17.528 | error | (18098) unhandled promise rejection: Cannot read property 'getRawPacket' of null
Unhandled | 2020-05-19 19:19:17.514 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

`

Grüße,

**Comment by guergen1** [comment]
Das Selbe hier...
js-controller 3.1.4
node.js 12.16.3
npm 6.14.4

**Comment by Bluemoon1978** [comment]
Hallo 
Habe das selbe Problem.


maxcul.0 | 2020-05-21 11:02:14.295 | error | (26662) unhandled promise rejection: undefined
-- | -- | -- | --
Unhandled | 2020-05-21 11:02:14.294 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().



js-controller 3.1.4
node.js 12.16.3
npm 6.14.4

Das mit dem "verschwunden" Port, bzw nur im deaktiviertem zustand editierbaren Port Eintrag ist schon seit mehr als einem Jahr.

Wünsche allen eine  schönen Vater/Männertag.

**Comment by D3ltorohd** [comment]
So hab das ganze noch mal zurück gesetzt und die Updates durchlaufen. Danach dann ein 
`iobroker rebuild maxcul --install`

Erst sah es so aus, als wäre der Fehler damit behoben gewesen, vorher mal in die Log geschaut. Leider taucht er dort wieder auf. Der Adapter resettet sich und läuft danach normal weiter.

**Comment by D3ltorohd** [comment]
@Bluemoon1978 @guergen1 
probiert mal das hier ::

**Comment by Bluemoon1978** [comment]
Leider keine änderung @D3ltorohd 
Die Meldung kommt jede Stunde, zZ ist nur ein Thermostat angelernt.

maxcul.0 | 2020-05-28 14:16:31.050 | info | (9222) Poll device maxcul.0.LKF0020235 : 1, 17
-- | -- | -- | --
maxcul.0 | 2020-05-28 14:15:33.057 | info | (9222) CUL FW Version: V 1.67 CUL868
maxcul.0 | 2020-05-28 14:15:31.050 | info | (9222) serialPort /dev/serial/by-id/usb-busware.de_CUL868-if00 is open!
maxcul.0 | 2020-05-28 14:15:31.045 | info | (9222) using serial device /dev/serial/by-id/usb-busware.de_CUL868-if00@38400
maxcul.0 | 2020-05-28 14:15:30.974 | info | (9222) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.maxcul, node: v12.16.3, js-controller: 3.1.4
host.HH-SRV.fritz.box | 2020-05-28 14:15:30.494 | info | instance system.adapter.maxcul.0 started with pid 9222
host.HH-SRV.fritz.box | 2020-05-28 14:15:00.478 | info | Restart adapter system.adapter.maxcul.0 because enabled
host.HH-SRV.fritz.box | 2020-05-28 14:15:00.477 | info | instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)
maxcul.0 | 2020-05-28 14:14:59.959 | info | (4818) Terminated (NO_ERROR): Without reason
maxcul.0 | 2020-05-28 14:14:59.958 | info | (4818) terminating
maxcul.0 | 2020-05-28 14:14:59.952 | error | (4818) unhandled promise rejection: undefined
maxcul.0 | 2020-05-28 14:14:59.951 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
maxcul.0 | 2020-05-28 14:14:47.934 | info | (4818) checkTimeIntervalFired
maxcul.0 | 2020-05-28 14:07:47.961 | info | (4818) Poll-Timeout: Reset Polling for device maxcul.0.LKF0020235 : 1, 16.5
maxcul.0 | 2020-05-28 14:01:47.951 | info | (4818) Poll device maxcul.0.LKF0020235 : 1, 17
maxcul.0 | 2020-05-28 13:15:47.939 | info | (4818) Poll device maxcul.0.LKF0020235 : 1, 17
maxcul.0 | 2020-05-28 13:14:49.945 | info | (4818) CUL FW Version: V 1.67 CUL868
maxcul.0 | 2020-05-28 13:14:47.937 | info | (4818) serialPort /dev/serial/by-id/usb-busware.de_CUL868-if00 is open!
maxcul.0 | 2020-05-28 13:14:47.931 | info | (4818) using serial device /dev/serial/by-id/usb-busware.de_CUL868-if00@38400
maxcul.0 | 2020-05-28 13:14:47.858 | info | (4818) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.maxcul, node: v12.16.3, js-controller: 3.1.4
host.HH-SRV.fritz.box | 2020-05-28 13:14:47.397 | info | instance system.adapter.maxcul.0 started with pid 4818
host.HH-SRV.fritz.box | 2020-05-28 13:14:17.379 | info | Restart adapter system.adapter.maxcul.0 because enabled
host.HH-SRV.fritz.box | 2020-05-28 13:14:17.377 | info | instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)
maxcul.0 | 2020-05-28 13:14:16.860 | info | (32607) Terminated (NO_ERROR): Without reason
maxcul.0 | 2020-05-28 13:14:16.859 | info | (32607) terminating
maxcul.0 | 2020-05-28 13:14:16.851 | error | (32607) unhandled promise rejection: undefined
maxcul.0 | 2020-05-28 13:14:16.850 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
maxcul.0 | 2020-05-28 13:14:04.830 | info | (32607) checkTimeIntervalFired
maxcul.0 | 2020-05-28 13:07:04.889 | info | (32607) Poll-Timeout: Reset Polling for device maxcul.0.LKF0020235 : 1, 16.5
maxcul.0 | 2020-05-28 13:01:04.845 | info | (32607) Poll device maxcul.0.LKF0020235 : 1, 17
maxcul.0 | 2020-05-28 12:15:04.836 | info | (32607) Poll device maxcul.0.LKF0020235 : 1, 17
maxcul.0 | 2020-05-28 12:14:06.843 | info | (32607) CUL FW Version: V 1.67 CUL868
maxcul.0 | 2020-05-28 12:14:04.834 | info | (32607) serialPort /dev/serial/by-id/usb-busware.de_CUL868-if00 is open!
maxcul.0 | 2020-05-28 12:14:04.828 | info | (32607) using serial device /dev/serial/by-id/usb-busware.de_CUL868-if00@38400
maxcul.0 | 2020-05-28 12:14:04.717 | info | (32607) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.maxcul, node: v12.16.3, js-controller: 3.1.4
host.HH-SRV.fritz.box | 2020-05-28 12:14:04.099 | info | instance system.adapter.maxcul.0 started with pid 32607
host.HH-SRV.fritz.box | 2020-05-28 12:13:34.080 | info | Restart adapter system.adapter.maxcul.0 because enabled
host.HH-SRV.fritz.box | 2020-05-28 12:13:34.078 | info | instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)
maxcul.0 | 2020-05-28 12:13:33.598 | info | (28261) Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2020-05-28 12:13:33.559 | info | (28261) Terminated (NO_ERROR): Without reason
maxcul.0 | 2020-05-28 12:13:33.557 | info | (28261) terminating
maxcul.0 | 2020-05-28 12:13:33.548 | error | (28261) unhandled promise rejection: undefined
maxcul.0 | 2020-05-28 12:13:33.547 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
maxcul.0 | 2020-05-28 12:13:21.532 | info | (28261) checkTimeIntervalFired
maxcul.0 | 2020-05-28 12:06:21.592 | info | (28261) Poll-Timeout: Reset Polling for device maxcul.0.LKF0020235 : 1, 16.5
maxcul.0 | 2020-05-28 12:00:21.592 | info | (28261) Poll device maxcul.0.LKF0020235 : 1, 17
maxcul.0 | 2020-05-28 11:14:21.539 | info | (28261) Poll device maxcul.0.LKF0020235 : 1, 17
maxcul.0 | 2020-05-28 11:13:23.544 | info | (28261) CUL FW Version: V 1.67 CUL868
maxcul.0 | 2020-05-28 11:13:21.536 | info | (28261) serialPort /dev/serial/by-id/usb-busware.de_CUL868-if00 is open!
maxcul.0 | 2020-05-28 11:13:21.531 | info | (28261) using serial device /dev/serial/by-id/usb-busware.de_CUL868-if00@38400
maxcul.0 | 2020-05-28 11:13:21.458 | info | (28261) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.maxcul, node: v12.16.3, js-controller: 3.1.4
host.HH-SRV.fritz.box | 2020-05-28 11:13:21.035 | info | instance system.adapter.maxcul.0 started with pid 28261
host.HH-SRV.fritz.box | 2020-05-28 11:12:51.020 | info | Restart adapter system.adapter.maxcul.0 because enabled
host.HH-SRV.fritz.box | 2020-05-28 11:12:51.018 | info | instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)
maxcul.0 | 2020-05-28 11:12:50.547 | info | (23875) Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2020-05-28 11:12:50.504 | info | (23875) Terminated (NO_ERROR): Without reason
maxcul.0 | 2020-05-28 11:12:50.504 | info | (23875) terminating
maxcul.0 | 2020-05-28 11:12:50.497 | error | (23875) unhandled promise rejection: undefined
maxcul.0 | 2020-05-28 11:12:50.496 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
maxcul.0 | 2020-05-28 11:12:38.477 | info | (23875) checkTimeIntervalFired
web.0 | 2020-05-28 11:11:06.415 | info | (1506) <==Disconnect system.user.admin from ::ffff:192.168.20.46 habpanel.0
web.0 | 2020-05-28 11:09:21.421 | info | (1506) ==>Connected system.user.admin from ::ffff:192.168.20.46
maxcul.0 | 2020-05-28 11:05:38.537 | info | (23875) Poll-Timeout: Reset Polling for device maxcul.0.LKF0020235 : 1, 16.5

**Comment by hoepps2802** [comment]
same with 
node.js v10.20.1
js controller  3.1.4

befor js controller  2.2.9

**Comment by Apollon77** [comment]
Feels like we mix different issues here!

I please need a more complete log for the "getRawPacket of null" problem, so not only the error, but also some line before this to see what happened before to be able to see reasons.

For the "request undefined" after a "drain" in the log see #45

**Comment by D3ltorohd** [comment]
> Feels like we mix different issues here!
> 
> I please need a more complete log for the "getRawPacket of null" problem, so not only the error, but also some line before this to see what happened before to be able to see reasons.
> 
> For the "request undefined" after a "drain" in the log see #45

So maybe here something to help...

`
host.iobroker | 2020-06-15 17:43:32.755 | info | Restart adapter system.adapter.maxcul.0 because enabled

host.iobroker | 2020-06-15 17:43:32.750 | info | instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)

maxcul.0 | 2020-06-15 17:43:32.203 | info | (17109) Terminated (NO_ERROR): Without reason

maxcul.0 | 2020-06-15 17:43:32.201 | info | (17109) terminating

maxcul.0 | 2020-06-15 17:43:32.188 | error | (17109) unhandled promise rejection: undefined

Unhandled | 2020-06-15 17:43:32.187 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

maxcul.0 | 2020-06-15 17:43:20.159 | info | (17109) checkTimeIntervalFired
`

**Comment by Apollon77** [comment]
Debug log please!

**Comment by hoepps2802** [comment]
Hello,

2020-06-18 04:04:20.243 - info: maxcul.0 (9010) checkTimeIntervalFired
2020-06-18 04:04:32.270 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-06-18 04:04:32.271 - error: maxcul.0 (9010) unhandled promise rejection: undefined
2020-06-18 04:04:32.301 - info: maxcul.0 (9010) terminating
2020-06-18 04:04:32.307 - info: maxcul.0 (9010) Terminated (NO_ERROR): Without reason
2020-06-18 04:04:32.869 - info: host.raspberrypi instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)
2020-06-18 04:04:32.877 - info: host.raspberrypi Restart adapter system.adapter.maxcul.0 because enabled
2020-06-18 04:04:33.921 - info: host.raspberrypi instance system.adapter.maxcul.0 started with pid 15273
2020-06-18 04:04:36.771 - info: maxcul.0 (15273) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.maxcul, node: v12.18.0, js-controller: 3.1.4
2020-06-18 04:04:38.102 - info: maxcul.0 (15273) using serial device /dev/ttyUSB0@38400
2020-06-18 04:04:38.149 - info: maxcul.0 (15273) serialPort /dev/ttyUSB0 is open!
2020-06-18 04:04:40.190 - info: maxcul.0 (15273) CUL FW Version: V 1.67 nanoCUL868


node.js v10.20.1
 js controller 3.1.4

**Comment by Apollon77** [comment]
I.only see info log entries here ... you need to go to instances - expert mode - column logstufe and set to debug für this instance

**Comment by Bluemoon1978** [comment]
Hier ist das Debug Log:

[https://pastebin.com/9Db37Jua](url)

Hoffe es kann dir Helfen

**Comment by Apollon77** [comment]
I need Debug log from such a crash :-)

**Comment by Bluemoon1978** [comment]
Um 9:53 ist der Chash.

**Comment by Apollon77** [comment]
Ha, ich blind :-) Danke

**Comment by Bluemoon1978** [comment]
> Ha, ich blind :-) Danke

Sind ja auch eine Menge an Zeilen. 
Ich habe zu Danken, wegen deiner unermüdlichen arbeit! Danke

**Comment by Apollon77** [comment]
Bitte nochmal frisch vom Github (versionsnummer ändert sich nicht) und dann nochmal ein Log (sorry) ich dachte ich hätte schon was geändert was ich aber hier im Log noch sehe ... und hab gerade nochmal logging aufgebohrt

**Comment by Bluemoon1978** [comment]
Neu Deinstallieren und Installieren oder nur Updaten?
Eben nur upgedatet, Log kommt mit dem ersten Fehler.

**Comment by Bluemoon1978** [comment]
Sorry das es mit dem LOG etwas gedauer hat.
ps bin habe heute Host noch auf 3.1.6 upgedatet

https://pastebin.com/wa5aeGKi

**Comment by Apollon77** [comment]
Please test again GitHub version

**Comment by D3ltorohd** [comment]
Über latest bekomme ich die neuste Version nicht ? Das muss ich von Hand über Github installieren ?

**Comment by bowao** [comment]
Versuchs mal mit 'Adapterinformationen aktualisieren'.
Bei mir erschien die Version 1.3.1 auch erst danach.

**Comment by Apollon77** [comment]
Das Repo wird an sich einmal am Tag aktualisiert ... ausser du machst das manuell über den Button unter "adapter "im Admin

**Comment by D3ltorohd** [comment]
Habs, Danke. Werde die Log beobachten und melde mich.
